#!/bin/bash

# Wedding Website Image Setup Script
# This script helps you set up your images

echo "🎉 Wedding Website Image Setup"
echo "================================"
echo ""
echo "📸 To add your photos:"
echo ""
echo "1. Prepare your photos with these names:"
echo "   - hero-bg.jpg (Main background, 1920x1080px)"
echo "   - story-1.jpg (First story, 800x600px)"
echo "   - story-2.jpg (Second story, 800x600px)"
echo "   - story-3.jpg (Third story, 800x600px)"
echo "   - venue.jpg (Venue photo, 1200x800px)"
echo "   - gallery-1.jpg (Gallery photo 1, 800x800px)"
echo "   - gallery-2.jpg (Gallery photo 2, 800x800px)"
echo "   - gallery-3.jpg (Gallery photo 3, 800x800px)"
echo "   - gallery-4.jpg (Gallery photo 4, 800x800px)"
echo ""
echo "2. Copy them into this 'images/' folder"
echo ""
echo "3. Refresh your browser (Ctrl+R / Cmd+R)"
echo ""
echo "💡 Tips:"
echo "   - Use JPG format for photos"
echo "   - Keep files under 500KB each"
echo "   - Compress at tinypng.com before adding"
echo ""
echo "✅ Current images in folder:"
ls -lh *.jpg 2>/dev/null || echo "   No images yet - add your photos!"
echo ""
echo "For more help, see images/README.md"
echo ""
